language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean install -Dlicense.skip=true -Dmaven.javadoc.skip=true -Dtest=org.eclipse.jetty.jaas.JAASLoginServiceTest

cache:
  directories:
    - '$HOME/.m2/repository'

